### PR TITLE
fix bug and add onDrop feature

### PR DESCRIPTION
**Pull request by zhangwei900808**

### CODE REVIEW

**Comment by zhangwei900808** [comment]
@bartaxyz Hi! I had fix bug please task a look and publish new version.

**Comment by zhangwei900808** [comment]
@bartaxyz I add onDrop feature if you have time please check my code and publish new version

**Review by bartaxyz — APPROVED** [review]

**Comment by bartaxyz** [comment]
Thank you for contributing 🙏 

Included in v0.3.0 release: https://github.com/bartaxyz/react-tree-list/releases/tag/v0.3.0-alpha.1

**Comment by zhangwei900808** [comment]
it's my pleasure！😊

**Comment by zhangwei900808** [comment]
@bartaxyz the version still 0.2.0 Have you publish to npm?
image

**Comment by bartaxyz** [comment]
Published now, sorry 🙏

**Pull request merged**
